on: 
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

permissions: read-all

env:
  GH_TOKEN: ${{ secrets.E2E_GO_TOKEN }}
  ISSUE_REPOSITORY: slsa-framework/slsa-github-generator
  #ISSUE_REPOSITORY: laurentsimon/slsa-on-github-test
  # WARNING: update build job if CONFIG_FILE changes.
  CONFIG_FILE: .github/configs-go/config-ldflags.yml

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2.4.0
      - run: |
          set -euo pipefail

          ./.github/workflows/scripts/e2e-push.sh
    
  args:
    if: github.event_name == 'push' && github.event.head_commit.message == github.workflow
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.ldflags.outputs.version }}
      commit: ${{ steps.ldflags.outputs.commit }}
      branch: ${{ steps.ldflags.outputs.branch }}
    steps:
      - id: checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4
        with:
          fetch-depth: 0
      - id: ldflags
        run: |
          set -euo pipefail

          THIS_FILE=$(gh api -H "Accept: application/vnd.github.v3+json" "/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" | jq -r '.path' | cut -d '/' -f3)
          BRANCH=$(echo "$THIS_FILE" | cut -d '.' -f4)
          echo "::set-output name=version::-X main.gitVersion=v1.2.3"
          echo "::set-output name=commit::-X main.gitCommit=abcdef"
          echo "::set-output name=branch::-X main.gitBranch=$BRANCH"

  build:
    if: github.event_name == 'push' && github.event.head_commit.message == github.workflow
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For the entrypoint.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@main
    needs: args
    with:
      go-version: 1.18
      # We cannot use ${{ env.CONFIG_FILE }} because env variables are not available.
      config-file: .github/configs-go/config-ldflags.yml
      evaluated-envs: "VERSION:${{needs.args.outputs.version}},COMMIT:${{needs.args.outputs.commit}},BRANCH:${{needs.args.outputs.branch}}"
      compile-builder: true
  
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo hello
  #         #exit 1
    
  verify:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.event.head_commit.message == github.workflow
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2.4.0
      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: ${{ needs.build.outputs.go-binary-name }}
      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: ${{ needs.build.outputs.go-binary-name }}.intoto.jsonl
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.2.0
        with:
          go-version: '1.18'
      - env:
          BINARY: ${{ needs.build.outputs.go-binary-name }}
          PROVENANCE: ${{ needs.build.outputs.go-binary-name }}.intoto.jsonl
        run: |
          set -euo pipefail
          
          ./.github/workflows/scripts/e2e.go.default.verify.sh

  if-succeeded:
    runs-on: ubuntu-latest
    needs: [build,verify]
    if: github.event_name == 'push' && github.event.head_commit.message == github.workflow && needs.build.result == 'success' && needs.verify.result == 'success'
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2.4.0
      - run: |
          set -euo pipefail

          ./.github/workflows/scripts/e2e-report-success.sh

  if-failed:
    runs-on: ubuntu-latest
    needs: [build,verify]
    if: always() && github.event_name == 'push' && github.event.head_commit.message == github.workflow && (needs.build.result == 'failure' || needs.verify.result == 'failure')
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2.4.0
      - run: |
          set -euo pipefail

          ./.github/workflows/scripts/e2e-report-failure.sh
