name: go schedule main SLSA3 config-ldflags-main-dir

on: 
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

permissions: read-all

env:
  GH_TOKEN: ${{ secrets.E2E_GO_TOKEN }}
  ISSUE_REPOSITORY: slsa-framework/slsa-github-generator
  #ISSUE_REPOSITORY: laurentsimon/slsa-on-github-test
  # WARNING: update build job if CONFIG_FILE changes.
  CONFIG_FILE: .github/configs-go/config-ldflags-main-dir.yml
  GO_MAIN: main.go
  GO_DIR: e2e/go

jobs:            
  args:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.ldflags.outputs.version }}
      commit: ${{ steps.ldflags.outputs.commit }}
      branch: ${{ steps.ldflags.outputs.branch }}
      main: ${{ steps.ldflags.outputs.main }}
    steps:
      - id: checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4
        with:
          fetch-depth: 0
      - id: ldflags
        run: |
          set -euo pipefail
          
          THIS_FILE=$(gh api -H "Accept: application/vnd.github.v3+json" "/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" | jq -r '.path' | cut -d '/' -f3)
          BRANCH=$(echo "$THIS_FILE" | cut -d '.' -f4)
          echo "::set-output name=version::-X main.gitVersion=v1.2.3"
          echo "::set-output name=commit::-X main.gitCommit=abcdef"
          echo "::set-output name=branch::-X main.gitBranch=$BRANCH"
          # Note: this must be the same path defined in the config file.
          echo "::set-output name=main::-X main.gitMain=$GO_MAIN"

  build:
    needs: [args]
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For the entrypoint.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.0.0
    with:
      go-version: 1.18
      # We cannot use ${{ env.CONFIG_FILE }} because env variables are not available.
      config-file: .github/configs-go/config-ldflags-main-dir.yml
      evaluated-envs: "VERSION:${{needs.args.outputs.version}},COMMIT:${{needs.args.outputs.commit}},BRANCH:${{needs.args.outputs.branch}},MAIN:${{needs.args.outputs.main}}"
      compile-builder: true
  
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           exit 1
    
  verify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2.4.0
      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: ${{ needs.build.outputs.go-binary-name }}
      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: ${{ needs.build.outputs.go-binary-name }}.intoto.jsonl
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.2.0
        with:
          go-version: '1.17'
      - env:
          BINARY: ${{ needs.build.outputs.go-binary-name }}
          PROVENANCE: ${{ needs.build.outputs.go-binary-name }}.intoto.jsonl
        run: |
          set -euo pipefail
        
          ./.github/workflows/scripts/e2e-verify.sh
  
  if-succeeded:
    runs-on: ubuntu-latest
    needs: [build,verify]
    if: needs.build.result == 'success' && needs.verify.result == 'success'
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2.4.0
      - run: |
          set -euo pipefail

          ./.github/workflows/scripts/e2e-report-success.sh


  if-failed:
    runs-on: ubuntu-latest
    needs: [build,verify]
    if: always() && (needs.build.result == 'failure' || needs.verify.result == 'failure')
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2.4.0
      - run: |
          set -euo pipefail

          ./.github/workflows/scripts/e2e-report-failure.sh
