# Creates workflow dispatch provenance with a pinned builder for verifier testdata.
on: 
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions: read-all

env:
  GH_TOKEN: ${{ secrets.E2E_GO_TOKEN }}
  ISSUE_REPOSITORY: slsa-framework/slsa-github-generator
  #ISSUE_REPOSITORY: laurentsimon/slsa-on-github-test
  # WARNING: update build job if CONFIG_FILE changes.
  CONFIG_FILE: .github/configs-go/config-noldflags.yml

jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2.4.0
      - run: |
          set -euo pipefail

          ./.github/workflows/scripts/e2e-dispatch.sh
  
  #TODO: support multiple config files.
  build:
    if: github.event_name == 'workflow_dispatch'
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For the entrypoint.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.0.0
    with:
      go-version: 1.18
      # We cannot use ${{ env.CONFIG_FILE }} because env variables are not available.
      config-file: .github/configs-go/config-noldflags.yml
